/**
 * ERK Type Definitions — Emotional Runtime Kernel
 *
 * These types define the contract between the FAR_NZY game state
 * and the adabt-core music orchestration system.
 *
 * Constitutional compliance:
 *   Law 1 — All numeric fields are deterministic (no Math.random())
 *   Law 2 — Cluster/leitmotif types enforce thematic continuity
 *   Law 3 — No main-thread DSP; types are data-only
 *   Law 4 — Serializable for IndexedDB persistence
 */

// ── Emotional State Vector ─────────────────────────────────────────────────

/**
 * Normalized 5-axis emotional representation of the current game moment.
 * All axes are clamped to [0, 1].
 *
 * This is the primary input to the Harmonic Transition Engine and
 * Leitmotif Mutation System.
 */
export interface EmotionalStateVector {
  /** Multiplier ladder position / unbanked stake ratio. Rises with consecutive scoring chains. */
  tension: number;
  /** Energy accumulation rate + mode progression. High in PRIME, volatile in FRENZY. */
  momentum: number;
  /** Proportion of total score at risk (unbanked / total). The bank-or-push signal. */
  risk: number;
  /** Disruption event density + FRENZY instability. Spikes during Wild Scatter, Heist, Rally. */
  chaos: number;
  /** Proximity to win/lose threshold. Approaches 1.0 as banked → WIN_SCORE. */
  resolution: number;
}

// ── Game State Snapshot (Receptor Input) ───────────────────────────────────

/** Energy mode from FAR_NZY farkleStore. */
export type EnergyMode = 'NORMAL' | 'PRIME' | 'FRENZY';

/**
 * Minimal snapshot of FAR_NZY game state needed by the Emotional State Receptor.
 * This decouples ERK from direct farkleStore imports — the host app passes
 * this snapshot, and the receptor produces an EmotionalStateVector.
 */
export interface GameStateSnapshot {
  energy: number;
  mode: EnergyMode;
  multiplierStep: number;
  banked: number;
  unbanked: number;
  chainLength: number;
  farkleCount: number;
  activeDisruptions: number;
  heistActive: boolean;
  rallyDecisionActive: boolean;
  winScore: number;
  gamePhase: 'idle' | 'playing' | 'win' | 'lose';
}

// ── Leitmotif System ───────────────────────────────────────────────────────

/** Thematic cluster IDs. Each cluster has distinct harmonic characteristics. */
export type LeitmotifCluster =
  | 'sacred'       // Cluster A — Celestial, reverential
  | 'profane'      // Cluster B — Demonic, aggressive
  | 'baroque'      // Cluster C — Dance-like, ornamental
  | 'atmospheric'  // Cluster D — Ambient, liminal
  | 'narrative';   // Cluster E — Processional, storytelling

/** Musical mode for harmonic generation. */
export type MusicalMode =
  | 'major'
  | 'minor'
  | 'dorian'
  | 'phrygian'
  | 'lydian'
  | 'mixolydian'
  | 'aeolian'
  | 'locrian';

/**
 * Seed profile for a single leitmotif (training track).
 * All procedural mutations are bounded by the envelope parameters.
 */
export interface LeitmotifSeed {
  /** Unique identifier (derived from track filename). */
  id: string;
  /** Display name of the source track. */
  name: string;
  /** Which thematic cluster this leitmotif belongs to. */
  cluster: LeitmotifCluster;
  /** Root pitch class (0–11, where 0 = C). */
  rootKey: number;
  /** Musical mode. */
  mode: MusicalMode;
  /** Reference BPM from analysis. */
  referenceBpm: number;
  /** Harmonic progression template as Roman numeral degrees. */
  harmonicProgression: number[];
  /** Mutation envelope — maximum allowed procedural deviation. */
  mutationEnvelope: MutationEnvelope;
}

/**
 * Bounded mutation parameters for deterministic procedural variation.
 * These caps are constitutionally mandated (Law 2 — Emotional Continuity).
 */
export interface MutationEnvelope {
  /** Maximum tempo deviation as a ratio (e.g., 0.15 = ±15%). */
  maxTempoDrift: number;
  /** Maximum transposition in semitones (e.g., 2 = ±2 semitones). */
  maxTransposition: number;
  /** Allowed instrument families for voicing swaps. */
  voicingFamilies: string[];
  /** Maximum number of simultaneous voice mutations per bar. */
  maxVoiceMutationsPerBar: number;
}

// ── Transition System ──────────────────────────────────────────────────────

/** Distance classification between two leitmotif clusters. */
export type ClusterDistance = 'same' | 'adjacent' | 'distant';

/**
 * A harmonic transition plan between two leitmotifs or clusters.
 * Generated by the Harmonic Transition Engine.
 */
export interface TransitionPlan {
  /** Source leitmotif/cluster. */
  from: LeitmotifCluster;
  /** Target leitmotif/cluster. */
  to: LeitmotifCluster;
  /** Distance classification determining transition strategy. */
  distance: ClusterDistance;
  /** Number of bars for the transition bridge. */
  bridgeBars: number;
  /** Pivot chord degree used for modulation (if applicable). */
  pivotDegree: number | null;
  /** Secondary dominant chain (for distant transitions). */
  dominantChain: number[];
  /** PRNG seed used to generate this plan (for replay). */
  seed: number;
}

// ── ERK Session State (Persistable) ────────────────────────────────────────

/**
 * Complete ERK session state, serializable to IndexedDB.
 * Captures the full emotional-musical state at any checkpoint.
 */
export interface ERKSessionState {
  /** Timestamp of this snapshot. */
  timestamp: number;
  /** Current emotional state vector. */
  emotionalState: EmotionalStateVector;
  /** Active leitmotif seed ID. */
  activeLeitmotifId: string;
  /** Active cluster. */
  activeCluster: LeitmotifCluster;
  /** Current effective BPM after mutations. */
  currentBpm: number;
  /** Current effective key (root + transposition). */
  currentKey: number;
  /** PRNG state for exact replay. */
  prngState: number;
  /** History of emotional state vectors (last N for smoothing). */
  emotionalHistory: EmotionalStateVector[];
  /** Pending transition plan (if mid-transition). */
  pendingTransition: TransitionPlan | null;
}
